# User
local_user: "{{ lookup('env', 'USER') }}"
local_home: "{{ lookup('env', 'HOME') }}"

# Paths
config_dir: "{{ local_home }}/.config"
local_bin:  "{{ local_home }}/.local/bin"

# Theme
colorscheme: "hackthebox"
font_family: "Hack"
font_size:   "15"
